services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-logger
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s 
      retries: 3
      start_period: 10s
      timeout: 5s
    labels:
      - "traefik.http.middlewares.ip-filter.ipwhitelist.sourcerange=${ALLOWED_IP}/32"